/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.tuki;

public class App {
    public String getGreeting() {
        return "Hola Diego!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("programacion estructurada");
    }
}
